### ISSUE TITLE
[1.11.2 - 1.0.4.6] Trough not giving back wheat

### ISSUE THREAD

**Issue by VallenFrostweaver** [capnkirok/animania#109]
Issue 1: If you stand on a trough or very close to it you sometimes cannot get the wheat back out of it that you placed in. It shows a short effect like it is being removed but then it does not. You have to be standing on the side that is placed (or gives a comparator signal). The work-around for this is to stand farther away and try again.

Issue 2: Besides this, I sometimes cannot remove wheat at all and have to break the trough. This is most often reproduced when automating the trough ( I used vanilla redstone stuff).

**Comment by Tschipp** [comment]
Can confirm both of the above. I also noticed them, but wasn't able to recreate them reliably. Thanks for pointing it out.

**Comment by VallenFrostweaver** [comment]
EDIT on issue 2: This can be reproduced by having a dropper feed wheat into the trough and stand close to the trough. The player picks up the wheat but it also visibly fills the trough though in reality it is not there as I can still add 3 pieces. Also happens more reliably when 2 troughs are touching.

**Comment by capnkirok** [comment]
This is because there's some code on the block that allows you to throw items at the trough to fill it (to enable droppers). And the code for removing wheat pops the item into the world. So there is a conflict based on the angle that the item is thrown. 

I'm going to leave this one as is until we add better automation (which will involve hoppers pulling directly from chests...)
