### ISSUE TITLE
Bug? Feature request? Animals should not be able to climb over troughs

### ISSUE THREAD

**Issue by calloatti** [capnkirok/animania#120]
![image](https://cloud.githubusercontent.com/assets/12817862/25320300/2ee248b4-287c-11e7-887b-9981ae7425a7.png)

First it doesn't look good aesthetically, and second they can climb over the fence when the trough is placed near it. (had to use double height fences)

Edit: Also, do they have to stay there 24/7? Cows, they are other things to do in life besides eating and drinking. You could walk around you know.

**Comment by capnkirok** [comment]
This one is a tough one. @Tschipp gonna DM you to explain the issue.

**Comment by capnkirok** [comment]
@calloatti here's the problem with this one. If I make the hitbox of the trough taller so the animals can't crawl over it, then they also can't reach the water or food in order to eat it. Also, pathing an animal that's size is greater than 1x1 block to a any single block in Minecraft is extremely difficult.

I'm going to think on this one a bit more, but I don't know if there's any better solution right now other than not placing your trough next to the fence.

**Comment by calloatti** [comment]
I suspected that would happen. Now, without knowing anything about how to code this, since it seems that cows can already kind of stick their heads thru fences, how about you make the troughs tall as a fence, but allow the animals to "eat" from their sides? Visually, they could have their heads over the trough while actually eating from the side.

This way they will not be able to have their bodies on top of the  trough, just their heads? Maybe clip the cows hitboxes to exclude part of the head?

If this is all nonsense, please ignore.

**Comment by capnkirok** [comment]
Well @calloatti and @Tschipp I'm gonna try out an idea from our ItemTexture guy (cy4n), which handles the eating via the collision with the block instead of in the AI script. This might do the trick, will report back.
