### ISSUE TITLE
Crash ticking block entity

### ISSUE THREAD

**Issue by Eufranio** [capnkirok/animania#186]
I'm a server owner and a lot of players who use Embers mod + Animania mod reported the following crash for us: https://hastebin.com/otelarasit.coffeescript

The player placed a Embers fluid pipe next to an Animania's Trough. When it connected, the game crashed. If you need more info, just let me know.

**Comment by Tschipp** [comment]
:(

**Comment by Tschipp** [comment]
Currently not able to recreate, Embers doesn't even launch on server for me, what version are you using?

**Comment by Tschipp** [comment]
Still cannot recreate... try using the latest version of Animania, I fixed some trough bugs there.

**Comment by Eufranio** [comment]
Can you launch the server? The versions are in the crash-report

**Comment by Tschipp** [comment]
Yeah I managed to get the server working with your version of embers, but I wasn't able to recreate the crash. I placed iron pipes, item pipes and pumps next to it, nothing happened

**Comment by Eufranio** [comment]
Server-side crash: https://hastebin.com/orojuxesuv.pl

**Comment by Eufranio** [comment]
Are the pipes with water?

**Comment by Eufranio** [comment]
Pretty reproducible:
![img](https://cdn.discordapp.com/attachments/319944126948966401/320338780215181312/2017-06-02_20.11.33.png)

**Comment by Tschipp** [comment]
Pipes were empty, idiotic, now that I think about it, because getCapability only gets fired when something wants to enter the tile.

**Comment by Jomik** [comment]
Happens for Immersive Engineering too. Guess it's the same 👍

**Comment by capnkirok** [comment]
Fix coming in just a few hours

**Comment by Jomik** [comment]
@capnkirok When will this be live for us on curse, etc.? :)

**Comment by capnkirok** [comment]
Around midnight CET

**Comment by WilliamBlaze** [comment]
i'v sport a similar issue with other pipe mods connection to the trough, it seems to only affect one side of the trough's model though. the side you can get a redstone comparater signal from is the only safe place you can pipe anything into it, placing any form of piping on the second block of the model causes instant crashes that have required an MCEdit to manually delete the item in order to restore world functionality. i'm not entirely sure if my experience with this issue is the same as the above considering i was using water pipe from Industrial craft 2, but i figured it was worth noting here, all things considered.

**Comment by capnkirok** [comment]
Thanks for the report. @Tschipp will poke around tomorrow.

**Comment by Tschipp** [comment]
@capnkirok I'm sure he will :P @Williamblaze can you provide a log, forge version and animania version?
