### ISSUE TITLE
Suggestions: The Poultry  for the mod

### ISSUE THREAD

**Issue by CrazyBeanie** [capnkirok/animania#211]
Hello mod creators, I was wondering what type of birds you were thinking on adding before I give you a couple of my suggestions.  I love birds and can't wait for you to, hopefully, add falconry and other bird types and species, but before I give you my suggestions I would like to know what you were thinking.

**Comment by montxen** [comment]
PS. I would only like the poultry to be named no falconry.  Also, I have one suggestion.  If you are doing falconry, then if it is possible can you add the poultry to hide in a shelter or under a tree when they see an untamed bird of prey that, to me, would make them seem like they are more realistic.

**Comment by capnkirok** [comment]
We don't really have anything set yet other than Falcons, Owls. Lots of others we're thinking about, please send your suggestions.

**Comment by montxen** [comment]
So I was thinking ducks, geese, turkeys.  There would be different species that have different roles, like eggs or meat, but for turkeys, it would usually be all meat types.  The ducks and geese can be found at any water source can swim but they float not have that weird jumping motion like the vanilla creatures.  Ducks are passive and would not run away, however, for geese, a gander goose, male goose, would attack the play if he/she gets too close to his family.  At night the waterfowl can sleep in an ocean, lake, or pond to get away from predators.  The wild turkeys would fly into or onto trees when it starts to get dark, however, I don't know if that is possible.  But once you tame or befriend turkeys and you build a shelter for them to have a type of roosting rung for them to jump on to sleep.  The tom turkeys would gobble when they hear loud noises and they will run away from people unless you hold seed and, I hear you may add corn, so they may come near for befriending.  Also, can you add the turkey's a strutting action for breeding?  That would be cool in my opinion.  I have more bird types and suggestions for those birds but I don't want to overwhelm you with too much to think about.

**Comment by montxen** [comment]
Also since you are adding falcons/owls or other birds of prey, I would also suggest guinea fowls, if you know what they are, if not, they are a chicken-sized gray bird with a small or large horn, depending on male and female, on their heads, they squawk or squeak, depending on gender, when there is something wrong in the surrounding around. They can be used to alert each other of predators, like wolves or falcons.  IRL the birds make different sounds.  In the game, a male will squawk with large horns and a female will squeak with small horns.  Like the turkeys, they would fly into the trees at night.  Also, a befriended guinea bird would alert all the other poultry to run and hide if a predator is near by or flying over them. What do you think? Too much?

**Comment by capnkirok** [comment]
Hey @CrazyBeanie  this is on our suggestions list now (much of it planned already). In an effort to clean up this git, I'm going to remove it so git only shows bugs.
