### ISSUE TITLE
[1.11.2-1.1.4] Incompatibility with Biome Bundle 1.11.2-v5

### ISSUE THREAD

**Issue by DeadPigman17** [capnkirok/animania#214]
If you create a world with using Animania and Biome Bundle mod (https://minecraft.curseforge.com/projects/biome-bundle) the game freezes, and the world doesn't load.

**Comment by Tschipp** [comment]
Interesting... do you have a log?

**Comment by capnkirok** [comment]
also did you see this? Are you using the recommended version?
![image](https://user-images.githubusercontent.com/9628379/27002505-6f8c40a8-4de4-11e7-8cf9-54f5b5aa7dca.png)

**Comment by PG85** [comment]
Solved this for OpenTerrainGenerator-1.11.2-v6 (not yet released), turned it into a log warning instead of a crash. The problem appears to be that these classes:

class com.animania.common.entities.peacocks.EntityPeafowlWhite
class com.animania.common.entities.peacocks.EntityPeachickWhite

have been added to biomes' mob spawning lists for spawning but the classes are not registered in the entity registry so I get a nullpointerexception when trying to fetch them via net.minecraftforge.fml.common.registry.EntityRegistry.getEntry(entityClass).

That's what it looks like anyway. Could it be that you forgot to register those two entities in the EntityRegistry?

One other thing, I'm looping over the entity registry and I see things like this registered:
textures/entity/cows/bull_angus.png. It is recognised as an entity of type creature and I do see custom cows spawning so that does appear to be working, it just looks like a texture has been registered as an entity which seems a bit weird. Might just be OTG ofc, not sure (entity registration changed a bit for Forge 1.11).

You can consider this issue closed anyway, will release OTG 1.11.2-v6 asap, it'll have a warning instead of a crash.

**Comment by capnkirok** [comment]
Thanks for the follow up!

- These are definitely registered. Also they spawn in game, so this is not the problem. Very strange.
- Re: resource location, yeah when I was originally working on this, I didn't understand why I needed the texture resource location in EntityRegistry, but I provided it, when it was just a lable. Should have through that one through a bit more. 

Thanks for the quick response.

**Comment by capnkirok** [comment]
Actually, I just found the issue with those two entities, which was they had a Resource Location conflict. So, we killed two birds with one stone. Har har.

**Comment by PG85** [comment]
Great to hear it, thanks for looking at this :)
