### ISSUE TITLE
Hamster ball texture missing 1.10.2

### ISSUE THREAD

**Issue by MtnDrew** [capnkirok/animania#229]
Did I mess it up? Because I'm getting the pink and black texture, and nobody has mentioned this at all, which is surprising considering how active this Github is. I control+F searched for "hamster" and came up with nothing so I decided to post here.

**Comment by capnkirok** [comment]
Strange. Are you on version 1.1.5? Showing screen cap using vanilla search and JEI search results: 
![image](https://user-images.githubusercontent.com/9628379/27262167-58cbbce0-5451-11e7-996b-27d63cbea571.png)

**Comment by capnkirok** [comment]
Try downloading a new version (delete the old) of 1.1.5 and see it it fixes it. It's weird that nothing would show up searching for hamster... because both Hamster Food and Hamster Egg show up for me in addition to all the balls....

Let me know how it goes.

Any other mods installed that might alter JSON/textures... like Chisel?

**Comment by capnkirok** [comment]
Hey I'm going to close this one since I haven't heard back. There are no other reports and it's working fine in the latest versions in our environments. Let me know if you find out the issue!
