### ISSUE TITLE
[SUGGESTION] Horse Meat

### ISSUE THREAD

**Issue by Sunconure11** [capnkirok/animania#231]
Well, it hasn't been done much, and yet horses are already used by many groups for meat.

**Comment by capnkirok** [comment]
This is a troublesome topic.

![image](https://user-images.githubusercontent.com/9628379/27264388-809622d4-547d-11e7-8700-ab1458bf9846.png)

**Comment by RaliaTheWolf** [comment]
If you do decide tomake this, you could maybe have a config option for it? And maybe have it off by default...

**Comment by Sunconure11** [comment]
A config option would be a good way to handle this. Plus, there are things in the game already that other cultures find taboo.

**Comment by hron84** [comment]
Or the whole vegan community against eating any meat in any game. Handling taboos can bring us too far from the point.

**Comment by capnkirok** [comment]
Ok, guys, this is in the next release. You'll find the item in the creative menu, but you'll have it add it manually to the Horse drops in the config.

**Comment by Deshiba** [comment]
@capnkirok I think its great you give the option, even though its a tough issue.

Rabbits are pets for a lot of people too, but they get butchered and bred for meat as well. There is no cultural stigma around them as far as I know. If you talk about cat and dog meat though, people tend to get upset. Huge stigma in the western world.

With cats, dogs and horses alike the stigma is mainly because of the close symbiotic relationship. But when it comes down to it, people will eat anything to stay alive.
