### ISSUE TITLE
Seed placement

### ISSUE THREAD

**Issue by 19nrussell** [capnkirok/animania#263]
I'm not for sure if this is intended but u can't place all seeds on grass blocks? aniamia newest verisan
mc-1.11.2

**Comment by Tschipp** [comment]
Oh god yes I broke seed placement... Use dispensers for now

**Comment by Kyrislian** [comment]
How does one use dispensers for seeds? XD (sorry, absolute newbie to this)

**Comment by Tschipp** [comment]
place dispenser, insert seeds, power dispenser

**Comment by Kyrislian** [comment]
Much thanks! :D

**Comment by Nephatrine** [comment]
Are dispensers supposed to place them on the ground like before? Maybe because I have RedstonePlusPlus or Quark that also add functionality to dispensers, but my dispensers just shoot the item out so I'd have to build a really slow timing circuit or it will just throw up all my seeds into the world in short order. :(

**Comment by Tschipp** [comment]
They are supposed to not shoot out seeds if a seed block is in front of the dispenser. Are they getting shot out even if there's a seed in front of the dispenser?

**Comment by capnkirok** [comment]
This is working fine, fixed in 1.11.2
