### ISSUE TITLE
trough not empty

### ISSUE THREAD

**Issue by bob0bob** [capnkirok/animania#349]
Are you suppose to top off the trough even though it is not empty.  It is basically empty but when you try to fill it, it just puts the water above the trough and pours out every.   The ability to top of the water trough even if that means it is half full and your bucket become empty.

**Comment by Tschipp** [comment]
A screenshot would be very useful

**Comment by capnkirok** [comment]
I *think* bob0bob is saying he wants to be able to manually replenish a trough without it being empty.

**Comment by bob0bob** [comment]
Yes.  Say it is somewhere between not full and not empty and you try to refill the trough.  The water doesn't go in the trough,  it is just like you empty the water on the ground.  As far at the effect.

**Comment by Tschipp** [comment]
Aha, yes. See, the problem is the bucket holds exactly 1000mB. If the trough contains 900mB of water, it will not let you refill it, because there's no bucket item for a bucket with 900mB of water. And if we made it so that it just fills up the trough to 1000mB and gives you back the empty bucket, you would lose 900mB of water, which can be devestaing for some modpacks, where water is a finite resource. **However**, you can refill the trough with pipes, even if it's not entirely empty.
