### ISSUE TITLE
Can I turn off breeding? 

### ISSUE THREAD

**Issue by Samillennium** [capnkirok/animania#392]
I would much rather the people on my server find resources and breed the animals by having to feed them something

**Comment by capnkirok** [comment]
Well, that kind of ruins the point of Animania, which is supposed to be more realistic and immersive.

Are you seeing overbreeding? Which version of Animania / Minecraft are you running?

**Comment by Samillennium** [comment]
I'm using the newest version so 1.12.2, and I like the different animals and types and how cute they are but if they are able to breed themselves then 
1. it takes some of the gameplay aspect of having to grow food for them so you can feed em, I mean you might as well just let them eat grass inside a pen at that point 
2. I can't be having to constantly throw in commands to kill off mobs in my world due to the world becoming overpopulated and lagging the heck out of my server.

**Comment by SSyl** [comment]
I'd have to agree with @Samillennium as well. We mostly use it on our server for the extra mechanics of having to feed them, give them water, the different types of animal products, and because the animals are cute in general. It adds some more depth to farming crops. The breeding gets a bit in the way of that since you'll eventually have to kill some of them which hampers the fun for some people.

You have an ambiance option to stop them from needing to eat/drink, so it makes sense to add 
 a breeding option that's off by default. Maybe a sort of "catnip" (cownip?) type food that when fed to a female and male of the same species could get them frisky would be a replacement. That way you could keep the feeding/drinking, but have a way to control pregnancy.

Side note: I did notice that some of my animals have been breeding through fences, so I've had to keep them separated in larger distances which is partially why I'd like breeding to be optional. However, on top of that, there's also been a few times I've noticed random bucks and bulls have spawned in the pen where I kept the females which then causes them to go in a bit of a breeding frenzy. I'm going to do some more testing to make sure that it's not something I'm doing or another mod that's interfering with it that's causing it to happen. I'm on MC 1.12 and Animania 1.35 for what it's worth.

**Comment by capnkirok** [comment]
Ok, some good arguments here. I will add this as a config option.

**Comment by capnkirok** [comment]
The way this will work...  if you enable in the config, you must hand feed the partners their favorite food to initiate breeding (every time, like vanilla).
