### ISSUE TITLE
Animals stuck in pits continue breeding

### ISSUE THREAD

**Issue by pckuijper** [capnkirok/animania#393]
o/ Enjoying the things animania adds to the game but we're running into a specific issue which is an endless breeding of animals when they get stuck inside water pools
![2017-10-16_21 06 39](https://user-images.githubusercontent.com/4448375/31630593-5186d40a-b2b7-11e7-8a14-89b59e77fb8d.png)
The attached photo is one of the smaller examples i've found of this, where a larger version of this actually caused me to lag out to 0tps.
Maybe a breeding cap of some sorts in an area could mitigate this issue?

**Comment by capnkirok** [comment]
Yes, I've seen this. It's because they are thirsty and they head to the water and then they stick around too long.... and then... well

I'm going to list this as a enhancement with two changes:
- Have the animals exit water asap if they are no longer thirsty
- Disable breeding if they are in water

I'm not sure what version of Animania you are on, but 1.3.5 has much better breeding controls. You can also make some lakes at the surface to keep animals from 'jumping in' the pit of fun.

**Comment by capnkirok** [comment]
There are a few other things going in in here causing the lag. Version 1.3.6 should be a huge relief.

**Comment by capnkirok** [comment]
Animals can no longer breed if they are 'stuck' in water. See 1.3.6+
