### ISSUE TITLE
Wrong Drops

### ISSUE THREAD

**Issue by Idioxic** [capnkirok/animania#402]
[animania.cfg.txt](https://github.com/capnkirok/animania/files/1419402/animania.cfg.txt)

### Expected Behavior
Cows and chickens drop prime meats

### Actual Behavior
Dropping regular meats

### Version of Minecraft, version of Animania, Single Player or Server
Minecraft 1.12.2
Animania 1.3.5
Single player

### Notes
Sometimes chickens or cows drop the correct "prime" meat, but it's unpredictable [

**Comment by capnkirok** [comment]
Hey @Idioxic there is some subtle variation with the prime meat drops.
![image](https://user-images.githubusercontent.com/9628379/32080146-5320d92e-baae-11e7-9dcb-25600e9e78e8.png)

So, Holsteins and Friesians only drop vanilla meats... they are dairy cows. And Leghorns only drop vanilla chicken.

And the other animals only drop the prime meats if they are fed and watered. Otherwise they drop vanilla.

Supposed to give you motivation to keep them happy. Can you verify that that's what you are seeing?

**Comment by capnkirok** [comment]
Ok, tested everything and it's working according to design. Though I admit it can be confusing. So, closing for now.

**Comment by Idioxic** [comment]
Yes you're correct, I'm not sure where I got prime beef and prime chicken from. There should be an option to completely override vanilla meat drops and allow "prime" cuts to be used in vanilla recipes. I find the vanilla meats useless.

**Comment by capnkirok** [comment]
Yeah, I think it's too complex now and need to give more control. I'll add this to the future enhancements list.

**Comment by Idioxic** [comment]
Thank you for your hard work and awesome mod :)
