### ISSUE TITLE
Spawn limit questions

### ISSUE THREAD

**Issue by Krhymez** [capnkirok/animania#443]
Currently the spawn limits are rather low, being 40 cows, pigs, sheep.. ect.
Are these limits per player or server wide?

Also does this effect breed animals? Lets say i set it to 2 cows, does that stop them from having any babies?

When playing on a server, if there are more than 20 players, then it may be a issue. Lets say everyone has 2 cows, does that mean none of them will breed?

If everything above is true, are there any plans to make "wild" and "breed" spawns different?

**Comment by capnkirok** [comment]
Hey @Krhymez 

Yeah, spawning has always plagued me. I put it in earlier since spawning seemed to be out of control for some users, and the AI wasn't as optimized. Performance is much better now, so I think I might make the limits optional.

- Spawn limit is linked to currently loaded and active chunks. On a widely populated server these levels look low.
- Yes, it affects breeding. I am going to add something to TOP/WAILA that says something like 'At Spawn Limit' to show you when this happens. Or I might also just turn this off as breeding was never really the problem, it was spawning.
- I added a config option to use 'manual' breeding. This prevents breeding in the wild, and defaults to MC style (you must feed them first).

All in all, I think you can raise your spawn limits for now. I am going to turn off the breeding prevention and make it a config option, I've had a number of questions, and seems like overkill (no pun intended).

**Comment by Krhymez** [comment]
We have been testing the numbers on the pack i am making Primal.  KiwiFrogg also works on the pack with me brainstorming issues.

With that being said, We doubled the spawn limit in the config and that seems to be ok.  In the next version of the pack i will enable "hand feed only" breeding. As i think it makes the most since "in vanilla you manually breed". This also prevents farms from growing out of control.  All of the "timers" in the mod have been 4x because our days are 96000 tick (4x vanilla length), so it "plays" better.

As for the spawn limits. How exactly is that handled?  I now understand it is server wide and in the chunks around a player but what stops a lot of animals from spawning in a small 3 chunk x 3 chunk area?  I was playing the mod before you fixed spawning, where 100s of animials would be in a small area. So what i am asking is, if i set the limit of cows to lets say 200, what stops 200 cows from spawning around a single play? is there a limit other than families in a single chunk?  I just want to make sure if i crank up these numbers, it wont be like it was 5 versions ago or so. 

When you turn off Breeding prevention, i think this would work a lot better than it is currently.  When this gets disabled, i can turn the Spawn limits back down. When i do this, does that mean once players farms reach the spawn limit, no animals will spawn in wild? I guess that is fine because there could be farmers on the server that sell animals... but i wonder if there is a way for the game to know the difference between a tamed and wild animal. (this could be a nice mechanic if so). This way there could be 2 spawn caps.  1 for wild animals and 1 for tamed animals. Once a player hand feeds an animal it becomes tamed or something.

Thank you for all your hard work, this mod has become a lot more stable this month alone.

Ps: i would love to see a few mobs.... mainly because they are kinda "jokes" in my pack.  there are these elephant and snake sounds that use to play a lot. The players always joke about the elephant and the snakes actually being in the game. Would be cool if that was possible.

**Comment by capnkirok** [comment]
Hey @Krhymez 

- So, spawn limits refer to 'chunks loaded', so slightly different than server wide... as players would need to be in loaded chunks on the server.
- Spawn limits currently prevent any animal from spawning if you are at your limit... that includes births. HOWEVER, I am changing this in the next release (see below). MC really controls how many animals spawn. Once the chunk is loaded, animania animals will not continue to spawn.
- Yes, if you use manual breeding, then no animals will breed/spawn in the wild. 
- Might add in two spawn caps, not sure. Let's see how this new version goes over

So, what will change in the next release:
- The spawn caps will only control vanilla replacements, not naturally spawning Animania animals including 'birthed' animania animals. This prevents the 'stuck on pregnancy' issue. I've tested this for the past week, and this is working really well. The overspawning issue from before it turns out was due to vanilla continually trying to spawn its animals and then having animania replace them. 

In your case, combining this with manual breeding would do the trick.

More mobs are coming.. snakes are on the list... not elephants yet... but  they can be domesticated... so... who knows!
