### ISSUE TITLE
Compatibility with Chickens Mod

### ISSUE THREAD

**Issue by Preminenc3** [capnkirok/animania#454]
Could you possibly have compatibility with the Chickens Mod (ones that add ore chicken etc...).

**Comment by Narwhal8** [comment]
Have you tried disabling the remove and replace function in the config?

**Comment by Preminenc3** [comment]
I don't want to disable the Animania chickens I am just wondering if there could be compatibility with that mod since Animania only effects Minecraft chickens.

**Comment by capnkirok** [comment]
Not sure what compatibility you are looking for. You want Chickens Mod to use Animania Nests? Or the other way around? Can you describe what you are looking for and I can comment on what is possible.

Spoiler Alert: I haven't played the Chickens Mod.

**Comment by Preminenc3** [comment]
If possible could you change their models so they match the Animania mods models and have them use Animania nests?

**Comment by capnkirok** [comment]
I'm sorry, but they can't use Animania models. That would be done on GenDeathrow's side anyway, and he'd have to do some 'morph' like coding to make it work. 

He might be able to use Animania nests. You can try to ping him, but not sure what response you'll get. Animania will be open source soon, so that might help with idea 2.
