### ISSUE TITLE
RE: #442 All non-vanilla liquids can be turned into vanilla milk

### ISSUE THREAD

**Issue by WesTroy** [capnkirok/animania#485]
#442 was closed. This is a follow-up to confirm:
Animania oreDicts every forge:bucketfilled item to listAllmilk.

Using only:
- Forge 14.23.1.2555 (Recommended) or .2564 (Latest at the time of #442)
- CraftStudio-1.0.0.93-mc1.12-alpha
- animania-1.12.2-1.4.3
- forestry_1.12.2-5.7.0.215 (for other buckets)
- jei_1.12.2-4.8.5.132
- jeiintegration_1.12.2-1.5.1.36 (for screenshots)

Screenshots:
https://imgur.com/a/9MAIo
(Three examples: Animania Slop, Animania Holstein Milk, Forestry Ethanol)
Shows listAllmilk for all forge:bucketfilled items.

Hope this helps! Mod is amazing and always improving. Keep up the great work.

**Comment by capnkirok** [comment]
It's not animania that is doing this. If you play this without the others, you will not receive the above results. Haven't identified the culprit yet.

**Comment by WesTroy** [comment]
Cool - thanks for the feedback. It's a very minor issue anyway - no other mods outside of Harvestcraft even oreDict any buckets (and that just adds listAllmilk to the Vanilla milk bucket, without affecting any forge:bucketfilled entries).

How can you tell, by the way, without other mods present? =) When you test it alone on your end, does the Slop Bucket contain the listAllmilk entry? When I use any oreDict read/dump tool, with any or no other mods, the Slop Bucket shows listAllmilk. Again, that requires a tool of some kind, so they could certainly all have some issue reading forge:bucketfilled oreDict entries. Of course, it's also possible you want Slop to be milk, and nothing is wrong there.

Anyway - some food for thought. Thanks again!

**Comment by cowardlyDog** [comment]
Well tbf I don't think there's any forge:bucketfilled added when you play with no mods, the only fluids in vanilla are water, lava and milk and they don't use forge bucket (obviously) they have their own name minecraft:water_bucket, minecraft:lava_bucket and minecraft:milk_bucket.

Maybe you could make all the milk and slop buckets the vanilla way and disable forge buckets so that you can oreDict them as listAllmilk without adding all the other forge buckets in the process.

Here are some screenshots showing all forge buckets are being oreDicted as listAllmilk

**Searching Forge buckets**
![2017-12-22_00 26 52](https://user-images.githubusercontent.com/30737871/34287823-446b6854-e6af-11e7-8e60-91598a7229da.png)
**Searching oreDict listAllmilk**
![2017-12-22_00 27 32](https://user-images.githubusercontent.com/30737871/34287824-447af580-e6af-11e7-9dca-ec0744c8ef99.png)

**Comment by capnkirok** [comment]
`

		ItemStack milkHolstein = UniversalBucket.getFilledBucket(ForgeModContainer.getInstance().universalBucket, BlockHandler.fluidMilkHolstein);
		ItemStack milkFriesian = UniversalBucket.getFilledBucket(ForgeModContainer.getInstance().universalBucket, BlockHandler.fluidMilkFriesian);
		ItemStack milkGoat = UniversalBucket.getFilledBucket(ForgeModContainer.getInstance().universalBucket, BlockHandler.fluidMilkGoat);
		ItemStack milkSheep = UniversalBucket.getFilledBucket(ForgeModContainer.getInstance().universalBucket, BlockHandler.fluidMilkSheep);
`

**Comment by capnkirok** [comment]
Yeah, checked with the forge team. It's not possible to use the Universal Bucket in conjunction with OreDictionary.
http://www.minecraftforge.net/forum/topic/62497-universalbucket-and-oredictionary-question/

Only solution is to use my own bucket.

**Comment by WesTroy** [comment]
Thanks for your research! This already-great mod improves with each release.

I'll leave this open so you can track for the future.

**Comment by capnkirok** [comment]
Ok, can't remove the Universal Bucket bc then the liquids can't be used for automation in pipes... so... we are just going to remove the OreDictionary entry for milk buckets. That means you'll have to exchange it in the crafting table for vanilla milk first. I think it's minor annoyance, but the best solution.
