### ISSUE TITLE
[1.12.2 - 1.4.3] Over-spawning

### ISSUE THREAD

**Issue by Draylynn** [capnkirok/animania#488]
### Expected Behavior
Less mobs.

### Actual Behavior
10+ /chunk and counting.

### Version of Minecraft, version of Animania, Single Player or Server
Animania 1.12.2 - 1.4.3
FML 1.12.2 - 14.23.1.2555

Having issues trying to control the spawning in this mod. I set the world to peaceful and set all the spawn limits/probs down to 1.
After about 20 mins, the tick ms starts to go up, after 40mins if I start killing animals, it makes no difference how many animals I nuke, they're now spawning out of control, with many different breeds of the same animals in a single chunk.
The configs are set to only breed when hand fed, I'm not noticing any lovey-dovey going on.
I am using BOP(Biomes O' Plenty) and most noticeably the meadows biome is worst affected.
Any tips? Am I doing something derpy?

[ModList.txt](https://github.com/capnkirok/animania/files/1585965/ModList.txt)

**Comment by capnkirok** [comment]
I've had two users report this. It doesn't happen for me, and I've done days and days of testing with BOP as well. It's very frustrating. 

But I can tell you what is happening to you. Vanilla mobs are spawning, then being replaced by Animania mobs. In Animania, there is a control that is supposed to control the spawning so that it stops replacing vanilla animals (and just kills them outright)) once you hit the limit, but somehow it is being bypassed. Any other mods you are using besides BOP? And are you on a server?

Meadow is in fact, the most populated biome (like Plains). 

In the next release (mid-Jan) we are going to stop 'replacing' vanilla spawns (and simply not spawn vanilla at all). And just spawn Animania animals naturally. Until then, it may be a matter of trying to find what mod or configuration is causing the vanilla animals to continue to be replaced.

**Comment by kchou94** [comment]
I believe I'm having the same problem.  I'm seeing a huge gathering of many animals in one spot, which is affecting my TPS.  I haven't attempted to breed them, and I haven't touched the configs.

<h2>Versions</h2>
<b>Animania:</b> 1.12.2-1.4.3<br>
<b>Minecraft:</b> 1.12.2<br>
<b>Forge:</b> 14.23.1.2575

<h2>Mod List</h2>

> AkashicTome-1.2-10.jar
> albedo-0.1.3.jar
> animania-1.12.2-1.4.3.jar
> AppleSkin-mc1.12-1.0.9.jar
> armorplus-1.12.2-11.8.3.29-beta.jar
> astralsorcery-1.12.2-1.8.4 (1).jar
> AutoRegLib-1.3-15.jar
> Baubles-1.12-1.5.1.jar
> BiomesOPlenty-1.12-7.0.0.2291-universal.jar
> Blur-1.0.4-14.jar
> Ceramics-1.12-1.3.3b.jar
> Chameleon-1.12-4.1.3.jar
> CharcoalPit-[1.12]-1.8.1.jar
> ChestTransporter-1.12-2.8.7.jar
> chiselsandbits-14.11.jar
> clarity-1.1.jar
> CodeChickenLib-1.12.2-3.1.5.331-universal.jar
> CoFHCore-1.12.2-4.3.8.27-universal.jar
> CoFHWorld-1.12.2-1.1.0.11-universal.jar
> comforts-1.12.2-1.1.0.jar
> CommonCapabilities-1.12-1.4.0.jar
> Controlling-3.0.5.jar
> CookingForBlockheads_1.12.1-6.3.17.jar
> CraftStudio-1.0.0.93-mc1.12-alpha.jar
> CraftTweaker2-1.12-4.0.11.jar
> CTM-MC1.12-0.2.3.9.jar
> CyclopsCore-1.12.2-0.11.0.jar
> davincisvessels-1.12-6.340-full.jar
> deepresonance-1.12-1.5.0.jar
> diethopper-1.1.jar
> dooglamooworlds-1.12-1.1.2.jar
> DynamicSurroundings-1.12.2-3.4.7.2.jar.disabled
> Earthworks-1.12-1.3.6.jar
> ElecCore-1.12.2-1.8.434.jar
> Exchangers-1.12-2.5.2.jar
> Farseek-1.12-2.2.2.jar
> FoamFix-1.12.2-0.8.2-Anarchy.jar
> Forgelin-1.6.0.jar
> ImmersiveCables-1.12.2-1.1.2.jar
> ImmersiveEngineering-0.12-75-core.jar
> ImmersiveEngineering-0.12-75.jar
> immersivepetroleum-1.12.2-1.1.5.jar
> immersivetech-1.12-1.3.4.jar
> industrialcraft-2-2.8.16-ex112.jar
> Inspirations-1.12.2-0.1.0.jar
> IntegratedDynamics-1.12.2-0.10.0.jar
> IntegratedTunnels-1.12.2-1.4.0.jar
> InventoryTweaks-1.63.jar
> itemscroller-1.12.0-0.11.0.jar
> IvToolkit-1.3.3-1.12.jar
> jei_1.12.2-4.8.5.138.jar
> jetorches-1.12.2-2.0.0.jar
> JustEnoughResources-1.12.2-0.8.5.27.jar
> KleeSlabs_1.12-5.3.2.jar
> Mantle-1.12-1.3.1.21.jar
> mcjtylib-1.12-2.5.0.jar
> MCMultiPart-2.4.1.jar
> modlist.txt
> moreoverlays-1.13-mc1.12.1.jar
> Morph-o-Tool-1.2-16.jar
> movingworld-1.12-6.342-full.jar
> natura-1.12-4.3.0.23.jar
> NetherEx-1.12-2.1.14.15.jar
> OpenComputers-MC1.12.1-1.7.1.43.jar
> OpenGlider-1.12.1-1.1.0.jar
> Pam's HarvestCraft 1.12.2b - Re-Balance Update.jar
> Quark-r1.4-120.jar
> RebornCore-1.12.2-3.5.4.176-universal.jar
> RecurrentComplex-1.4.6.jar
> RedstoneArsenal-1.12.2-2.3.8.20-universal.jar
> RedstoneFlux-1.12-2.0.1.2-universal.jar
> refinedstorage-1.5.29.jar
> Reliquary-1.12.2-1.3.4.728.jar
> roughMobs1.0.14-1.12.2.jar
> rustic-0.4.3.jar
> Scannable-MC1.12-1.6.2.13.jar
> smarthud-1.12-1.0.4.jar
> SoundFilters-0.10_for_1.12.jar
> SpartanShields-1.12.2-1.4.jar
> StevesCarts-1.12.2-2.4.13.69.jar
> stg-1.12.2-1.2.3.jar
> StorageDrawers-1.12.1-5.3.3.jar
> StorageDrawersExtras-1.12-3.1.0.jar
> Streams-1.12-0.4.1.jar
> TConstruct-1.12-2.8.1.49.jar
> thedragonlib-1.12.2-5.2.0.jar
> theoneprobe-1.12-1.4.19.jar
> ThermalDynamics-1.12.2-2.3.8.16-universal.jar
> ThermalExpansion-1.12.2-5.3.8.36-universal.jar
> ThermalFoundation-1.12.2-2.3.8.22-universal.jar
> topaddons-1.12.2-1.2.1.jar
> ToughAsNails-1.12.2-3.1.0.73-universal.jar
> Traverse-1.12.1-1.3.1.jar.disabled
> UniDict-1.12.2-1.9b.jar
> WanionLib-1.12.2-1.4.jar
> Waystones_1.12.1-4.0.17.jar
> WearableBackpacks-1.12.2-3.1.0.jar

**Comment by Protected** [comment]
Some of my users have reported this as well.

**Comment by grugsy** [comment]
having the same issue. mob count rapidly grows out of control. animals group up en masse near light sources like in old beta mc making villages/player housing lag considerably. (worst in BoP meadows)

https://www.modlister.com/user/grugsy

**Comment by capnkirok** [comment]
Thanks guys. Working on an overhaul of spawning right now (see two bumps up).

**Comment by capnkirok** [comment]
Ok, I've got this fixed in the development server. What a complicated system Minecraft uses.

So, can confirm what was happening. Vanilla animals were re-spawning bc they had not reached their internal limit. These animals were then replaced by my code and turned into Animania animals. And the cycle continued. Limits should have prevented this, but were not working in certain conditions (on servers with certain other mods).

What will change:
- Vanilla animals will simply be removed (not replaced)
- Animania animals will be spawned using normal MC code
- Spawn Limits wil no longer be necessary

This prevents the 'replacement' cycle, as all vanilla will simply be removed, and Animania animals will follow default limit behavior.
