### ISSUE TITLE
Default spawn rates are too high

### ISSUE THREAD

**Issue by Sunconure11** [capnkirok/animania#50]
https://www.dropbox.com/s/m20xxxxe5dl80b0/Screenshot%202017-03-10%2008.04.06.png?dl=0

This causes a noticeable TPS drop.

**Comment by capnkirok** [comment]
Delete your config and try again.

**Comment by Winddbourne** [comment]
I agree! I thought it might be an issue simply because the pack I'm working on ATM has eternal daylight . . . but most default creatures have a spawn weight of around 8; and Animania has upped in to nearly three times that high by default. 

Currently I've adjusted Chicekns, Cows, and Pigs to a spawn weight of 8, and put peacocks, hamsters, etc . . . at a mere five. It isn't even because of TPS alone . . . I want other things to spawn into the world as well. I'm using Lycanite's mobs as well for more aggressive wildlife during the endless daylight. 

I can't even imagine if I was trying to use this with Mo'Creatures. lol. Though for me, as I said, I've made the issue worse simply be eliminating the night period where spawning would stop, some of these animals would despawn, and mobs would come out to play. In normal play perhaps a weight somewhere between 8 & 10 would be reasonable.

**Comment by capnkirok** [comment]
Yes, I should have renamed these variables.... i'll send a warning out.

**Comment by Sunconure11** [comment]
Issue still happens even after clearing my config file.

**Comment by capnkirok** [comment]
In config, set all probability rates to 30 or 40. Max spawn size should be set to 2 or lower.

**Comment by capnkirok** [comment]
FYI, I've changed the config names in 1.0.3 (in Dev version) so they will automatically do this for everyone's config. Thanks for the input guys.
