### ISSUE TITLE
Excessive procreation / spawning conflict [1.11.2, 1.12]

### ISSUE THREAD

**Issue by HeberonYT** [capnkirok/animania#532]
### Actual Behavior
Hello
There is an excessive reproduction of animals in the world, I was only playing 30 minutes and around me was full of horses, cows and toads.

### Version of Minecraft, version of Animania, Single Player or Server
Minecraft 1.11.2
Animania 1.4.4

### Screenshots encouraged
![2018-01-25_13 56 55](https://user-images.githubusercontent.com/13698597/35412771-df56dcec-01e2-11e8-8e26-90e08eca8aec.png)

**Comment by capnkirok** [comment]
Well, it looks like horses from this picture. Can you send me your config and your modlist please?

**Comment by HeberonYT** [comment]
Config: https://pastebin.com/raw/pUAhXLUu

I am on a server forge 1.11.2-13.20.1.2588
In the picture only horses are seen, but in the farms of my house I have chickens, cows and frogs, all increased unexpectedly and exaggerated, I have to kill the overpopulation.
**ModList:**
creativecoredummy
itemphysic
Micdoodlecore
Forgeendertech
adhooks
craftstudioapi
animania
bibliocraft
chunkpregenerator
codechickenlib
creativecore
customnpcs
cyclopscore
dailies
dissolution
dungeondq
ecomod
evilcraft
evilcraftcompat
galacticraftcore
galacticraftplanets
mjrlegendslib
extraplanets
extrautils2
fairylights
mobtotems
overlord
guideapi
llibrary
iceandfire
ironbackpacks
jei
subcommonlib
fashion
lostcities
malisiscoremalisisdoors
minions
mob_mash
mowziesmobs
netherportalfix
nei
personalcars
placeableitems
lteleporters
sophisticatedwolves
tickprofiler
totemic
umbraluxvampirismteamlapen-lib
waila
worldedit
air_support

**Comment by capnkirok** [comment]
Your config looks fine. It can't be procreation bc gestation timer is set at 24000 ticks, and I see mostly adults. Which means the problem is Spawning (very different). You can verify this by changing to manual breeding in the config or just watching an open area to see if tons of babies are being born.

As for spawning, my code no longer handles its own spawns. It's handled by Forge + Minecraft. There is only a simple registry entry which spawns animals when new chunks are generated. Do any of your mods regenerate chunks?

**Comment by HeberonYT** [comment]
I do not want to be contradictory, but I do not think it is Spawning.
I know this because there must be a couple of animals to get out of control.
By the way, until now I have detected that only horses, chickens, cows and frogs are out of control, they are all animania. 
This image shows that the pigs do not have overpopulation.
![2018-01-25_18 36 31](https://user-images.githubusercontent.com/13698597/35419906-412ec16a-0200-11e8-807d-6370bff05a05.png)

I use "chunkpregenerator" but I do not think it has to do with this issue, since there is only overpopulation where there are players, that is, loaded chunks.

**Comment by QAngelusQ** [comment]
I also am having similar issues on Sponge Server 1.12.2 - Animania 1.4.4

I changed all the family sizes to 1 in the config file

I compared HeberonYT's mod list with my own for similar mods and removed them. (with the exception of WAILA & JEI)

Using the same seed and spawn area, after about 20 minutes of being idle I come back to this: despite any changes to the config or mod files

![2018-01-26_01 58 35](https://user-images.githubusercontent.com/35056074/35428623-3181e484-023e-11e8-8a7a-9f00511344d3.png)

**Comment by capnkirok** [comment]
Thanks both. I can't tell you how upsetting and confusing this is to me. With the last update, I pulled all of my fancy spawning code and left it all to Minecraft to handle. This is all there is now:
`
EntityRegistry.addSpawn(EntityCowFriesian.class, AnimaniaConfig.spawn.spawnProbabilityCows, 1, maxFam, EnumCreatureType.CREATURE, getBiomes(BiomeDictionary.Type.PLAINS));`

**Comment by capnkirok** [comment]
Oh and @HeberonYT interstingly... Cows, Chickens, and Horses extend the vanilla counterparts. There may be something going on with the super class... this may be a good clue (or a red herring), we'll see.

**Comment by capnkirok** [comment]
Ok, reporting back. I've just finished 3 hours of testing on my server. I did not see procreation. And I didn't see a huge amount of animal spawns. I did see more spawns than I wanted to see in the Plains in particular. 

![2018-01-26_20 49 11](https://user-images.githubusercontent.com/9628379/35457855-9ca4fd5e-02da-11e8-9704-96dacc29229c.png)

**Comment by QAngelusQ** [comment]
Everytime I tested it was only 1 player (me)

Its starting to look like sponge because this is the before:
![2018-01-26_15 46 55](https://user-images.githubusercontent.com/35056074/35461173-b32c73ac-02b4-11e8-87f2-79992d254912.png)

And this is after adding sponge:
![2018-01-26_16 04 07](https://user-images.githubusercontent.com/35056074/35461181-bfe06a36-02b4-11e8-8314-1520ea0d2688.png)

I initially suspected sponge at first and changed some settings a while back but it didn't change anything. Also HeberonTY didn't have it on his/her mod list so I was hoping it was some other mod we had in common. I'll play around with the sponge cfg some more and will hopefully find a fix on my end and will report back ^_^

**Comment by HeberonYT** [comment]
I do not use sponge, it is a server only with forge 1.11.2.
On the server I'm just connected, and observe the images of how everything comes back to fill up with animals, and by the way, now if it's affecting the TPS of my server, it's falling down to 8 tps, In part, it will be because of the block updates when most of that lawn is consumed.

I have not been able to test only with the Animania mod, since my server is private and a series is made from there, therefore, I can not eliminate the other mods.
I did not see this problem in version 1.4.3

By the way, I guess that activating the limit of entities in the sponge configuration could prevent this from happening, but forge does not have those options. In addition, it would continue consuming many resources trying to spawnear entities reached the limit.

![2018-01-26_16 18 56](https://user-images.githubusercontent.com/13698597/35463657-5b1d6a92-02b7-11e8-8c76-c4cbdf208d46.png)
![2018-01-26_16 21 46](https://user-images.githubusercontent.com/13698597/35463672-6df3ce72-02b7-11e8-9357-0b4caace604b.png)
![2018-01-26_16 27 57](https://user-images.githubusercontent.com/13698597/35463673-6e09a01c-02b7-11e8-9f2d-8a56d1e8eb70.png)

**Comment by capnkirok** [comment]
Really weird that it's just Plains. I have a theory I'm going to test. Will report back later.

**Comment by capnkirok** [comment]
@HeberonYT Give this version a try and let me know how it goes. You'll need to try a fresh world and remove your config.

This one reduces spawning of all animals in Plains in particular, along with fewer families.

https://www.dropbox.com/s/qi6l7dy2olyhuf5/animania-1.11.2-1.4.4.jar?dl=0

**Comment by HeberonYT** [comment]
@capnkirok Hello, tomorrow Sunday I could review it, right now it is not possible for me, thanks for your attention.

**Comment by PhoenixRiver** [comment]
Version: animania-1.12.2-1.4.4
Forge: forge1.12.2-14.23.1.2555
Minecraft: 1.12.2

I don't know how this affects things but I have a bug also submitted to Ice and Fire (see Curse) because there is a setting in that mod:

dragons {
    # True if dragons can despawn. Note that if this is false there may be SERIOUS lag issues.
    B:canDragonsDespawn=true

When I set this to false it caused the number of sheep on my local plains biome to explode... there was some breeding (some young sheep) but mostly adults.

This might be a related to this problem?

For reference here is a link to the Ice and Fire bug report:

**Comment by capnkirok** [comment]
@PhoenixRiver that setting doesn't appear to be in the 1.11.2 version

**Comment by capnkirok** [comment]
@HeberonYT reporting back. So, I downloaded all of the mod on your modlist and created my own server. After several attempts, I finally saw some out of control spawning... frogs. Those little green specs... are hundreds of them. So now I have a test bed.
![2018-01-28_23 22 23](https://user-images.githubusercontent.com/9628379/35487990-6c4c0afe-0482-11e8-900a-1892e45f3e0e.png)

**Comment by PhoenixRiver** [comment]
Would you prefer me to create a new ticket for it then? Though I guess a solution for 1.11.2 might well work for 1.12.2 ...

**Comment by capnkirok** [comment]
@PhoenixRiver that is interesting. Let's keep it in this thread and I will do more testing.

**Comment by HeberonYT** [comment]
@capnkirok Hello
I have reviewed the update that you sent me, and so far the amount of mobs remains at 150, goes up and down, but remains at that average.
It seems that this worked for me.
Do you recommend continuing to use that file? or do I expect the official version?
Thank you

**Comment by capnkirok** [comment]
@HeberonYT great news. Yes, I also see the same thing. However, there is still an issue with the frogs. Let me see if I can get an official update out asap (tomorrow at the latest).

**Comment by thundR** [comment]
Just wanted to affirm that this is a problem on 1.12. There are hundreds of sheep around me, and just sitting and watching the world I saw at least 5-6 babies born in about 30 seconds. Since newer versions of MC have mobs with collision boxes, it's getting hard to play the game. I cannot kill them fast enough. I also have fire and ice installed. 
Enigmatica 2: Expert 1.04

https://gyazo.com/05e5cf9fcb77f3cc50a1a3a45fd8230b

**Comment by capnkirok** [comment]
@thundR there could very well be a cross-interaction with ice and fire, with 3 cases confirmed, thanks for confirming 'birthing' is an issue for you and not spawning.

- I also see an issue with Frogs - This is due to mob caps sometimes not working on Ambient creatures (this is a Minecraft issue, but I can add caps manually)
- Also could be an issue with Sponge

Working on all 3 on this thread.

**Comment by SalmonSays** [comment]
I've been following this thread closely in the hopes of a fix, I'm afraid I can confirm that I'm having problems on 1.12.2 without Ice and Fire. I'm running a forge 2587 server and had enough animals spawning on a meadows biome to bring the server to its knees. I can't entirely discount the possibility that it's a birthing issue, but I'm reasonably confident it's a spawning issue as I recall seeing a lot of adult animals within a very short span.

**Comment by PhoenixRiver** [comment]
Hello :)

Having played for a dozen more hours I can confirm that despite having
turned set dragons to despawn again I still have a problem... it seems
that the sheep are now numerous enough that they are just breeding to
maintain population as fast as I can kill them and there are so many
in one (large) area of forest (they seem very poor at navigating out
of it) however once they leave that forest for the open plains they
spread fast and it is all I can do to kill the ones that come out
while playing the game. I have tried a number of times to go in an
wipe them out but it appears that by going there I am waking more and
more of those on the other side of the group by having the chunks load
and they are then breeding/spawning to remove any gains I make on this
side. I should mention that the problem now appears to be primarily
breeding, not spawning - one or two do spawn but most of the problem
seems to be the spread of younger sheep from breeding.

My config seetings for sheep currently read:
Families: 1
Spawn limit: 10
Probability Sheep: 4

Can and should I change these and if so which way does the probability
go (higher is fewer sheep or lower is fewer sheep?) and can I set them
to zero?

Thank you for your work on this problem and if there is anything I can
do to potentially help I'm happy to (though my main world has a few
hundred hours in it so I'm hoping I might be able to fix that one and
not have to restart (though at least I'll have a better idea what I'm
doing!)

River

**Comment by SalmonSays** [comment]
I should also mention, my newly generated config for Animana 1.4.4 on 1.12.2 doesn't have a text option for "Spawn Limit" anywhere.

**Comment by QAngelusQ** [comment]
In Animania 1.4.4 the spawn code was completely rewritten so that the spawn limit shouldn't be needed hence it was removed (as seen in the changelog)

Also I found that adding changing the gestationTimer by adding 2 Zero's helped my spawn problem in the short term (haven't played enough to see any long term effects) which seems silly but I would recommend trying it just to see if it works. This way the problem's sample size can increase and could give the mod author more information about this issue.

**Comment by capnkirok** [comment]
@QAngelusQ the gestation timer is based on server ticks. Generally speaking, 24000 ticks is about 1 minecraft day (24 minutes). But I've seen server tick time behave differently. This a great clue, thanks, will add this to the list.

**Comment by c0mical** [comment]
Hi, just to add I'm getting an overpopulation of horses (bray?) running 1.12.2 with the 1.4.4 versions. a few other mods inc forestry (which also adds new entities) but no ice and fire

**Comment by PhoenixRiver** [comment]
I tried clearing out the sheep with tnt but until I stood next to the tnt it failed to explode due to the server skipping so many ticks due to the number of sheep... needless to say I blew myself up and apparently a lot of the sheep didn't take damage... something I've noticed happens when using a sword too - presumably due to the server skipping ticks as well :( :(

I've regenerated my animania config file and changed the gestation period longer by a power of 10 and reset the sheep family setting 1 but left the probability at 8 (I don't know if higher or lower here means more sheep, can you tell me?)

I'll get back to you if this fixes the problem.

**Comment by capnkirok** [comment]
Ok, thanks. I am also working on a permanent fix.

**Comment by glindsey** [comment]
As much as I hate to say it... my daughter and I saw this same problem (or at least one really similar) on our server, but in our case it was with deer, sheep, cows, and horses primarily, in a Biomes O' Plenty Chapparal. We don't have Sponge or Ice & Fire loaded, although we do have a ton of other mods. The crowd was extensive enough at one point to exceed the server watchdog tick threshold (60 seconds) and force-kill the server. Had to do a mass /kill to fix it; on the plus side we now have enough food to last us months. 😅 

My theory has been that we'd been mining extensively underneath the area where the crowd of animals was (keeping the chunk loaded), and that the conditions were perfect to cause a breeding explosion. I dropped spawn rates in the config file and disabled automatic breeding, and so far I haven't seen the problem recur -- but it hasn't been very long yet since I made the change.

Anyways, just thought I should chime in since others have had some issues in this area. Overall the mod is fantastic, keep up the great work!

**Comment by MauveCloud** [comment]
@thundR I think that command will also kill off villagers, which might not be desirable (some of the screenshots above have villages visible).

**Comment by PhoenixRiver** [comment]
That command would and I have set up base in a village so I'm not
going to run it without modification in  my world. I think it should
be possible to run something like /kill @e[type=sheep] in my case to
clear out the sheep but that depends on the entity name being
unchanged for Animania - which I suspect is not the case.

**Comment by MauveCloud** [comment]
After leaving breeding as non-manual for several days in single-player, my plains seem rather overpopulated with cows, to the point that I could kill them off and have more beef and leather than I know what to do with (making it seem pointless to try to build a farm or pen for them), though not as bad as others here.
My modlist: https://paste.ubuntu.com/26509111/

Screenshot:
![2018-02-02_11 35 02](https://user-images.githubusercontent.com/8942955/35752312-4b99fdde-0810-11e8-9aa5-88cfe16a9982.png)

**Comment by MidnightsFX** [comment]
I am also seeing this issue with a number of different species of animals.

I had been play-testing this exact modpack and had not had any similar kind of issues in singleplayer, so to me it seems like the world being a hosted server seems to be making a significant difference.

There seems to be two initial issues to me:
- Animals are spawning in loaded but not viewed chunks after generation (seeing new pigs, foul & cows in current biome)
 - Spawning seems to follow existing types largely (removing all animals from a number of chunks, leaving & returning seems to spawn new ones of the 'appropriate biome type' but not necessarily the breed that existed prior)

The bulk of animals I am seeing are around loaded or occasionally loaded chunks, traveling farther out to chunks I have been to before- but are not being kept loaded do not exhibit an overflow of animals.

Don't know if that's helpful at all but that seems to be everything I have observed so far.

1.10.2 - Forge Server
Ice & Fire, Animania... (I can retrieve the whole modlist if needed)

**Comment by capnkirok** [comment]
Thank you everyone for all of the input and information. It's really, really helpful.

After banging on this problem for the week, the best way to handle it is to reinstate the Spawn Limits. I guess I didn't realize how effective these were before.

Spawn Limits will only apply to animals that are naturally spawned through WorldGen or natural entity re-spawns, it will not apply to new births. 

I will also make some changes to procreation, to ensure the gestation timer is working properly.

Plan to have this update out tomorrow at the latest. Thank you for your patience.

**Comment by PhoenixRiver** [comment]
Thank you for all your work on this, I can understand that it is a
very nebulous problem to fix and that we've not been able to provide
very consistent reported effects (so reproduction of the problem has
been harder) but thank you for giving a good go at a general and
(hopefully) working fix. This is what separates the okay from the good
mod writers :)

**Comment by MidnightsFX** [comment]
@capnkirok Thanks for your quick work on this!

**Comment by HeberonYT** [comment]
@capnkirok 
great! Thank you very much.
