### ISSUE TITLE
animals stuck in troughs

### ISSUE THREAD

**Issue by kyothedestroyer** [capnkirok/animania#538]
### Version of Minecraft, version of Animania, Single Player or Server : Minecraft ver 1.12 animania ver 1.4.3
![2018-01-30_17 35 56](https://user-images.githubusercontent.com/35978714/35597495-6d0b2bce-05e4-11e8-8419-3fd743ea05f0.png)
![2018-01-30_17 36 17](https://user-images.githubusercontent.com/35978714/35597496-6e817d96-05e4-11e8-9fb8-349a01939daa.png)
![2018-01-30_17 36 38](https://user-images.githubusercontent.com/35978714/35597498-6feb5fda-05e4-11e8-8580-a507cb1ec728.png)
![2018-01-30_17 36 56](https://user-images.githubusercontent.com/35978714/35597499-70e4020c-05e4-11e8-905b-3988aa42e23d.png)
![2018-01-30_17 37 08](https://user-images.githubusercontent.com/35978714/35597502-71f95ad4-05e4-11e8-8d8e-65d66fbd0833.png)

**Comment by capnkirok** [comment]
Well, that's not good. I would recommend you update to 1.4.4, as I completely redid all pathing to the troughs.. but with the current spawning issues, would wait until 1.4.5, which should come this weekend.

If you want to try 1.4.4 be my guest. It works fine in SP, but shows some issues on modpacks on server. Otherwise just wait a couple of days.
