### ISSUE TITLE
New baby animals appearing in existing chunks after switching to manual breeding

### ISSUE THREAD

**Issue by MauveCloud** [capnkirok/animania#539]
### Expected Behavior
With manual breeding selected, and other options default, baby animals should only appear in newly-generated chunks or when deliberately breeding animals.

### Actual Behavior
Animals, including baby animals (mostly calves, it seemed, though I also saw a few lambs and chicks), appeared in areas that I had previously cleared of animals, implying they had spawned there.

Having an option to deliberately make this happen is okay, especially for a player who is somehow having trouble finding enough Animania animals to get started with breeding, but it should not be enabled by default.

I notice in the config there are probabilities for different animals to spawn in "loaded" chunks, not just newly generated chunks.  I have temporarily set these to 0 in my game, but I'm not certain that's really the right way to deal with this.

### Steps to Reproduce
1. Set the config for manual breeding.
2. Kill off the animals in a given area.
3. Travel far enough away for the chunks to unload, then come back.
4. Notice the new animals in the previously-clear area.

### Version of Minecraft, version of Animania, Single Player or Server
Minecraft 1.12, Animania 1.4.4, SSP peaceful

**Comment by capnkirok** [comment]
You are correct. The initial spawning of families does not take manual breeding into consideration. Make sense to alter this.

**Comment by MauveCloud** [comment]
Update: after setting the probabilities to 0, my game is crashing with IllegalArgumentExceptions (though Animania is not in the stacktrace so I'm not entirely certain of this yet) - I'm guessing Animania passes the value along to Minecraft's "1 in N" chance function without treating 0 as a special "disable" value the way most other mods do.

**Comment by capnkirok** [comment]
I have a check on family size, but not on probabilities... I love your subtle digs. Yes, I can add. If you don't want to spawn an animal... set the Spawn of that animal to false... don't try to force it with probabilities.

**Comment by MauveCloud** [comment]
The wording of the config entries confused me.  I still want animals to appear in _newly generated_ chunks, but not in re-loaded chunks (unless they were already there), which is why I thought setting the probabilities to 0 would help, but I expect setting the spawn to false would prevent any new Animania animals (of the chosen types) from appearing in newly generated chunks as well.  Or am I still misunderstanding?

**Comment by capnkirok** [comment]
Manual Breeding in next release prevent children spawning in families

**Comment by SSyl** [comment]
@capnkirok I've read over this thread a few times and I'm a little confused as to what this change will entail.

> Manual Breeding in next release prevent children spawning in families.

Does this mean that if I have manual breeding enabled, I won't see any children or baby animals generated in new chunks at all? I'd have to manually breed animals in order to have any child animals appear in my world? Or am I misreading this?

**Comment by capnkirok** [comment]
Hey @MauveCloud - Yeah, sorry it's not clear in the config. I have no control of New Chunk Spawning vs. Re-added Spawning. They use the same parameters and methods. The text is not clear.

@SSyl you are reading this correctly. Maybe this is not what people wanted. I felt it added an additional protection layer against overspawning. Let me know if this is not correct. I can also just make this a separate config.

**Comment by SSyl** [comment]
@capnkirok It is nice to see small families with baby animals when exploring out in the wild because it adds a bit of flavor to the world and there's also a "cute" factor to it.

That said, it's not a game-breaking feature if you have to disable them for performance reasons. Although, if there's an easy way for you to implement this as a config option I definitely wouldn't be opposed to that..

Also, just as a side note, I really appreciate how responsive and receptive you are to issues and suggestions about your mod. Definitely one of the best mod devs out there.
