### ISSUE TITLE
Conflict with ExtraUtils 2

### ISSUE THREAD

**Issue by RedBullSlurpie** [capnkirok/animania#546]
### Expected Behavior
Make the Chicken ring
### Actual Behavior
I can't make the Chicken ring from ExtraUtils 2 because Animania has disabled default spawning of vanilla chickens, and it seems none of animania's work with ExtraUtils 2, I think i've tried all versions of chickens and none seem to work for crafting the XU2 chicken ring. Can any thing be done about this so I don't need to remove your mod ?

### Steps to Reproduce
Try to craft a XU2 Chicken ring

### Version of Minecraft, version of Animania, Single Player or Server
1.12.2, Animania 1.4.4, SP.

**Comment by QAngelusQ** [comment]
One thing you can do is use the mod [CraftTweaker](https://minecraft.curseforge.com/projects/crafttweaker) to alter the recipe of the chicken ring so that it doesn't require the lasso with a chicken.

An easier thing would be to go into the animania config file ("Animania.cfg") and set to false "replaceVanillaChickens" so that chickens from minecraft spawn again. The only drawback would be that you won't get any chickens from the Animania Mod.

**Comment by BryanBoru** [comment]
IIRC you can use a bat in lasso to make comparable ring as well

**Comment by MauveCloud** [comment]
If you're making an Angel Ring, you need a lassoed bat as part of the final crafting recipe, but the Chicken Wing Ring is the first step.  Sometime after seeing this issue, I tried to come up with a CraftTweaker script to allow using Animania chickens instead, but it ended up allowing an empty lasso in the recipe, which wasn't what I wanted (possibly because I'd trimmed away too many of the NBT tags).  Setting replaceVanillaChickens to false and finding a vanilla chicken in new chunks definitely works (that's what I did, before this issue was posted).

**Comment by capnkirok** [comment]
Two other notes/options:
- If you turn ReplaceVanilla chickens to false. You get both Animania and Vanilla chickens. You would have to set SpawnAnimaniaChickens to false in order to not get Animania chickens.
- Ping the ExtraUtils2 author. He should technically be using an instanceof EntityChicken instead of the literal class name. Just like the chickens mod and Cooking for Blockheads do. It's literally one line of code, and that would fix the issue on his side (which is where the problem is)

**Comment by MauveCloud** [comment]
I don't think he's using the class name.  I think he's using the entity id string from NBT data.  However, I'm having trouble finding which other NBT tags are actually used, even when searching decompiled source.

**Comment by Tschipp** [comment]
I mean he must be storing all the entity nbt, so he can just create the entity from nbt and check if it’s instanceof EntityChicken.

**Comment by MauveCloud** [comment]
That explanation won't wash.  The chicken wing ring can be made in a vanilla crafting table, which afaik doesn't allow callbacks for such a check - it has to have the NBT tag requirements determined ahead of time.  The recipe shown in JEI seems to indicate that only 2 NBT tags are actually important, presumably one of which is the animal type name.  However, a lassoed Plymouth Rock Rooster (which I had planned to use as a starting point) has a bunch of extra NBT data, some of which could easily vary between different roosters.

/ct hand gives me:
<extrautils2:goldenlasso>.withTag({Animal: {IsChickenJockey: 0 as byte, Watered: 1 as byte, HurtByTimestamp: 0, ForgeData: {}, Attributes: [{Base: 6.0, Name: "generic.maxHealth"}, {Base: 0.0, Name: "generic.knockbackResistance"}, {Base: 0.29, Name: "generic.movementSpeed"}, {Base: 0.0, Name: "generic.armor"}, {Base: 0.0, Name: "generic.armorToughness"}, {Base: 16.0, Name: "generic.followRange"}, {Base: 2.0, Name: "generic.attackDamage"}], Invulnerable: 0 as byte, FallFlying: 0 as byte, ForcedAge: 0, PortalCooldown: 0, AbsorptionAmount: 0.0 as float, FallDistance: 0.0 as float, InLove: 0, DeathTime: 0 as short, ForgeCaps: {"dsurround:emojidata": {as: 0, es: 0, et: 0}}, HandDropChances: [0.085 as float, 0.085 as float], PersistenceRequired: 1 as byte, id: "animania:rooster_plymouth_rock", Age: 1, Motion: [0.0, -0.0784000015258789, 0.0], Leashed: 0 as byte, Fed: 1 as byte, UUIDLeast: -8982019054603266029 as long, Health: 6.0 as float, LeftHanded: 0 as byte, Air: 300 as short, OnGround: 1 as byte, Dimension: 0, Rotation: [-105.665985 as float, 0.0 as float], UpdateBlocked: 0 as byte, HandItems: [{}, {}], ArmorDropChances: [0.085 as float, 0.085 as float, 0.085 as float, 0.085 as float], EggLayTime: 999, UUIDMost: -1363397757600968936 as long, Pos: [151.5, 69.0, 241.5], Fire: -1 as short, ArmorItems: [{}, {}, {}, {}], CrowTime: 198, CrowDuration: 0, CanPickUpLoot: 0 as byte, HurtTime: 0 as short}, Animal_Metadata: {Health: 6.0 as float, MaxHealth: 6.0 as float}, No_Place: 0 as byte})

Unfortunately, even if I try to use that as-is in a CraftTweaker recipe, it fails, because apparently CraftTweaker doesn't parse those "as" keywords even though it outputs them 😖  The CraftTweaker documentation is very limited when it comes to the syntax allowed for NBT Tags.

**Comment by MauveCloud** [comment]
Update: I found an "itemsMatch" method in XU2's ItemGoldenLasso, implented for the ICustomRecipeMatching interface, which seems to check for the presence of an "Animal" tag and a matching "id" tag, and I think there might also be a way to add custom recipes for things like this to Extra Utils 2 - there is an assets/recipes folder in the jar, but it's empty, so there are no examples to work from.

I tried making this script with CraftTweaker:
```
recipes.addShaped(<extrautils2:chickenring>,
[[<ore:feather>, <ore:ingotIron>, <ore:feather>],
[<ore:ingotIron>, <extrautils2:goldenlasso>.onlyWithTag({Animal:{}, id: "animania:rooster_plymouth_rock"}), <ore:ingotIron>],
[<ore:gemRedstone>, <ore:ingotIron>, <ore:gemRedstone>]]);
```
and JEI showed the recipe as if an empty golden lasso would work.  However, when actually attempting to craft, both an empty lasso and a lassoed Plymouth Rock Rooster had no crafting output.

**Comment by MauveCloud** [comment]
Another Update: I remembered about the "/ct recipes" command, and using the "/ct recipes hand" on the Chicken Wing Ring gave me this:
```
recipes.addShaped(<extrautils2:chickenring>, [[<minecraft:feather>, <minecraft:iron_ingot>, <minecraft:feather>], [<minecraft:iron_ingot>, <extrautils2:goldenlasso>.withTag({Animal: {id: "minecraft:chicken"}, No_Place: 1 as byte}), <minecraft:iron_ingot>], [<extrautils2:ingredients>, <minecraft:iron_ingot>, <extrautils2:ingredients>]]);
```
I'm not sure why it picked up "minecraft:feather" as the top corner ingredients when JEI makes it clear that the recipe would accept any feather there (including Animania feathers).  It's less clear whether the original recipe uses the ore dictionary for the iron ingots and resonating redstone crystals, but I finally got the recipe somewhat working:
```
recipes.addShaped(<extrautils2:chickenring>,
[[<ore:feather>, <ore:ingotIron>, <ore:feather>],
[<ore:ingotIron>, <extrautils2:goldenlasso>.withTag({Animal: {id: "animania:rooster_plymouth_rock"}, No_Place: 1 as byte}), <ore:ingotIron>],
[<ore:gemRedstone>, <ore:ingotIron>, <ore:gemRedstone>]]);
```
This recipe also apparently allows re-using the now-empty lasso (which still has some residual NBT tags) to make another ring, which doesn't match normal behavior without the script.  However, a freshly-crafted lasso (or one pulled from the creative menu, which afaik comes out the same) is not usable for making the ring, which is good.

It might be possible to set up an array and loop through it to get all the Animania chickens, but that's beyond my CraftTweaker skills (the CT documentation only covers how to do something similar for metadata).

**Comment by CharCharthemonkey** [comment]
@MauveCloud u could also just turn off the chicken ring in the XU2 config which will give u back the original angel ring recipe

**Comment by MauveCloud** [comment]
Really?  I would have guessed that disabling the chicken ring in XU2 config would also implicitly cause a cascade of disabled recipes for other items that relied on the item.  However, I tried it, and it produces an easier recipe for the angel ring, not the "original" recipe from XU1 which involved unstable ingots and a nether star according to https://ftb.gamepedia.com/Angel_Ring_(Extra_Utilities)

**Comment by capnkirok** [comment]
Hey guys, I'm closing this one as there's nothing I can do on my side. Please re-open if you see it otherwise.
