### ISSUE TITLE
Odd issue with server

### ISSUE THREAD

**Issue by SuddenlyH2O** [capnkirok/animania#60]
I am having a very strange issue.. I want to try this mod but it was spawning too many mobs and causing lag.. that's not the strange issue though. So I removed Animania from my server in an attempt to fix the lag but was confused when I logged back in and still saw Animania mobs on my screen. They were not moving and massive amounts pilled onto each other. My F3 entity count was skyrocketing from 30 to over 3000. The server wasn't lagging, it was just my client.
[Current mod list](https://paste.ee/r/M7lkq/0)

**_RECAP_**
Client (with Animania installed) logged into server (without Animania) and Animania mobs still appeared on client's screen causing entity count to skyrocket.

**Comment by capnkirok** [comment]
The existing server spawn issue was fixed in 1.0.2, but would have required cleanup of entities. 

To fix your current problem, you'll have to remove it from both client and server to get rid of the Animania mobs, otherwise the client will continue to try to replace vanilla animals/spawn Animania in the world (and leave ghosts).

It could be that you have a mod that is causing a conflict, not sure. But when you've done the above, try changing the Config options for 'Remove Vanilla Pig/Cow/Chicken' to false, and then try your world again. Let me know if you still see the entity count go very high.

**Comment by SuddenlyH2O** [comment]
Sorry for the last response..
My problems have disappeared with the following..
- Updated to Animania 1.0.3
- Regenerated the config
- Changed the configs options you suggested
- Made sure the server & client configs were the same

Thanks for the help.
