### ISSUE TITLE
[1.10.2] Leghorn Chick Not Growing Up

### ISSUE THREAD

**Issue by MokahTGS** [capnkirok/animania#83]
I have a naturally spawned leghorn chick that is not growing up into an adult.  Is that normal or just a bug?

**Comment by capnkirok** [comment]
Hey @MokahTGS ! I just tested and things are working as intended, though I do see a few questions about this one.

Couple things to know:
- Chicks need to have food and water (to be happy) in order to grow. You'll can hand feed them if you want.
- It takes just over 1 full MC day for a chick to grow. It will need to be happy the entire time... or it will take longer
- You can change the setting in the config so they grow faster if you want... the setting is growth per tick and it set to 200 by default. Just set it to 20 or something and spawn in a new chick to see.

PC
